import type { Metadata } from "next";
import localFont from "next/font/local";
import MainLayout from "../components/MainLayout";
import "../styles/globals.scss";
import { LayoutProvider } from "../context/LayoutContext";

const notoSans = localFont({
  src: "../../public/fonts/NotoSans/NotoSans-vf.woff",
  variable: "--font-noto-sans",
  weight: "100,900",
  display: "block",
  preload: true,
});

export const metadata: Metadata = {
  title: "React Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSans.variable}`}>
        <LayoutProvider>
          <MainLayout>{children}</MainLayout>
        </LayoutProvider>
      </body>
    </html>
  );
}
